### ISSUE TITLE
Crashes increased in android app after implementing smartlook sdk

### ISSUE THREAD

**Issue by kailashchand-arcgate** [smartlook/smartlook-mobile-issue-tracker#53]
**Platform**
Android

**Technology**
React native

**Build instructions [optional]**
React Native version: 0.63.3, 
gradle dependencies : 
com.android.tools.build:gradle:3.5.3
com.google.gms:google-services:4.3.4

**Rendering [optional]**
N/A

**Affected devices [optional]**
Galaxy Tab S6 Lite,
Alcatel JOY TAB
Realme 3 Pro

**Smartlook SDK version**
smartlook-react-native-wrapper": "^0.31.0"

**Summary**

- In our project we are delivering our app as per different CPU architectures. that is "armeabi-v7a", "x86", "arm64-v8a", "x86_64".
- App orientation locked.
- App equipped with Firebase Crashlytics and Smartlook.
- Firebase Crashlytics also shows that Android devices are not rooted.
- All crash occurred only in Android devices. iOS device is working fine.

**We found our app crashes on:**
 1. On app launch
 2. Sometimes user rotate the phone but Smartlook capture the new oriented snapshot which might be a crash cause. https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/28#issuecomment-722507543
 3. Sometimes user not recorded in Smartlook but our Firebase Crashlytics recorded his crash logs.
 4. Smartlook continuously increasing the user app data which might be crash issue on low storage devices.
 5. Smartlook slightly increase the CPU usage which might be another cause of Crash with low memory devices.
 6. All crashes occurred only on "**arm64-v8a**" & "**armeabi-v7a**" ABI.
 7. Our app is not using any kind of video manipulation but still facing "**MPEG4Writer**" in Google Play console log. See Screenshot. https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/20#issuecomment-710706591
 8. Our app is orientation locked but Smartlook capturing and showing it. See screenshot.

**Steps to reproduce [optional]**
N/A

**Example Project [optional]**
N/A

**Relevant logs and/or screenshots**
**Firebase crashlytics logs**
Session summary 1.6.0 (145) 10 Galaxy Tab S6 Lite Jan 19, 2021, 4:17:35 PM
Crashed: Thread :  SIGSEGV  0x0000000000000010
#00 pc 0x71cc588748  
#01 pc 0x71cc5d4fe8  
#02 pc 0x72c97a203c libc.so 

Session summary 1.6.0 (145) 10 realme 3 Pro Jan 11, 2021, 10:32:26 PM
Crashed: Thread :  SIGSEGV  0x0000000000000010
#00 pc 0x77e3fab748  
#01 pc 0x77e3ff7fe8  
#02 pc 0x78ea10f094 libc.so 

Session summary 1.6.0 (143) 9 Alcatel JOY TAB Jan 17, 2021, 4:23:42 AM
Crashed: Thread :  SIGABRT  0x0000000000000000
#00 pc 0xa8de7ca6 libc.so 
#01 pc 0xa9ce07f0 libstagefright.so 
#02 pc 0xa9ca9256 libstagefright.so 
#03 pc 0xa9ca9372 libstagefright.so 
#04 pc 0xa9c7987b libstagefright.so 

**Google Play Console Log**
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
pid: 0, tid: 0 >>> com.rdiscovery <<<
backtrace:
  #00  pc 000000000001cca6  /system/lib/libc.so (abort+58)
  #00  pc 00000000000ac254  /system/lib/libstagefright.so (abort_with_message(char const*)+24)
  #00  pc 00000000000ac370  /system/lib/libstagefright.so (__ubsan_handle_mul_overflow_minimal_abort+24)
  #00  pc 000000000007c879  /system/lib/libstagefright.so (android::MPEG4Writer::Track::threadEntry()+7248)
  #00  pc 0000000000063305  /system/lib/libc.so (__pthread_start(void*)+22)
  #00  pc 000000000001de69  /system/lib/libc.so (__start_thread+24)

![Error](https://user-images.githubusercontent.com/69476046/105368898-ffcc6f80-5c27-11eb-8c5d-8d10985322e8.png)
![smartlook (1)](https://user-images.githubusercontent.com/69476046/105370586-bc730080-5c29-11eb-8248-114c241773d7.png)

**Comment by githubbla** [comment]
most crashes on android 7.1.1, with 1GB ram.
even on x86 emulator.
even with disabled in smartlook admin

**Comment by kailashchand-arcgate** [comment]
Hi @SenNeonoveNoci  , Is there any update?

**Comment by kailashchand-arcgate** [comment]
Hi, @SenNeonoveNoci , I have reviewed your all crash related issues/threads and decided to **upgrade my smartlook version from 0.31 to 0.39**. Now I have noticed in my last two weeks after smartlook upgrade, I'm facing most of the crashes was accouring in following OS: 
- Android 5.1.1
- Android 7, 
- Android 7.1.2
- Android 8.0
- Android 8.1.0
- Android 9.0 
- Android 10
- Android 11
All these crashes are related to **libc.so**, **libart.so** and **libyoga.so**

**Comment by AndrewMorsillo** [comment]
Seems related to https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/65 and https://github.com/smartlook/smartlook-mobile-issue-tracker/issues/28 (the details in the thread, not the original issue 28 which is fixed)

**Comment by SchneiderOr** [comment]
Hey, Is there's any new about this issue?
We consider dropping Smartlook due to the huge amount of crashes using the react-native module

**Comment by krystofcelba** [comment]
Hey, sorry for waiting. We are going to release a new version soon. It'll be fixed there.

**Comment by tjerkw** [comment]
Still not fixed. I'm using the latest version of smartlook for flutter ^3.0.3

And the app freezes and crashes

**Comment by SchneiderOr** [comment]
We removed smartlook few months back, terrible dev experience and zero support from the dev team..
All the best.
